-keep class * extends ir.mahdiparastesh.fortuna.misc.BaseNumeral { public <init>(...); }
-keep class ir.mahdiparastesh.fortuna.misc.HumanistIranianCalendar
-keep class ir.mahdiparastesh.fortuna.misc.Numerals
