-keep class * extends ir.mahdiparastesh.fortuna.misc.Numeral { public <init>(...); }
-keep class ir.mahdiparastesh.fortuna.misc.HumanistIranianCalendar
-keep class ir.mahdiparastesh.fortuna.misc.Numerals
